### ISSUE TITLE
Black trainer video during loading 

### ISSUE THREAD

**Issue by amolgoeldatakalp** [datakalp/Vajra-Hands-App#11]
Samsung note 20 held in landscap
![Screenshot_20230412_144557_Chrome](https://user-images.githubusercontent.com/122245973/231414987-65271ed8-0354-4e9c-8eba-bb436fbe42a3.jpg)
e mode.

The trainer video was periodically  going black at a high frequency.

**Comment by datakalp** [comment]
Observed the same on One Plus Nord. This is after recording the video, but before pressing "Know your HAIgenie" score. 
This screen is for the user to assess his own recording, and re-record if she wants to. For that assessment, the user should be able to see the guide video being played side-by-side with the replay of her hand washing motions.

**Comment by anubhutiGupta** [comment]
Closing this as now, guide video plays as well along with user recorded video, during replay
