### ISSUE TITLE
Re-record Prompt after the feedback screen should be reworded.

### ISSUE THREAD

**Issue by datakalp** [datakalp/Vajra-Hands-App#15]
Currently it says something like "If you are not happy with the recording, press the red button to record" 
That is fine for recording *before* submitting it for the feedback. 
After the feedback is asked for and given, the prompt should simply say "Press the red button to record another episode"

**Comment by anubhutiGupta** [comment]
The prompt is reworded now; the issue can be closed after checking the suitability of the suggested prompt message in real mobile interface.

**Comment by anubhutiGupta** [comment]
closing this, since prompt is reworded now
