### ISSUE TITLE
Migrate Metadata from local SQL to Mongo DB on azure

### ISSUE THREAD

**Issue by datakalp** [datakalp/Vajra-Hands-App#17]
As discussed with Aniket ji and Anubhuti today morning. This will automatically resolve the P0 issues we keep having with the local SQL db errors.

**Comment by aniketpingley** [comment]
QualEtho has implemented this in the middleware. Datakalp has to switch the call to our API. Instructions already shared with  @anubhutigupta2409

**Comment by aniketpingley** [comment]
1) Data migration from SQL to MongoDB for existing video metadata done. 2) Integration with new backend API for storing video metadata into MongoDB is also done. 3) Use of MySQL is discontinued. 4) Required backup of video metadata tables is in place.
