### ISSUE TITLE
Guide Animation does not start for iPhone

### ISSUE THREAD

**Issue by anubhutiGupta** [datakalp/Vajra-Hands-App#6]

**Comment by datakalp** [comment]
Reported by multiple iPhone users. Let's test this after the current version is hosted on datakalp.com

**Comment by anubhutiGupta** [comment]
Closing this as guide animation now shows up on i-phone after we switched to using a public URL for the guide video

**Comment by anubhutiGupta** [comment]
Closing this as guide animation now shows up on i-phone after we switched to using a public URL for the guide video
