### ISSUE TITLE
Multiple "Follow Animation" prompts can be seen after recording has started

### ISSUE THREAD

**Issue by anubhutiGupta** [datakalp/Vajra-Hands-App#7]
Process Flow :-

1. Successful Login by the user.
2. Successful hand detection of the user.
3. Successful finishing of the counter from 3..2..1
4. User sees more than one (multiple) prompts suggesting "Please follow the guide while performing the Hand Wash"

![WhatsApp Image 2023-04-06 at 21 31 02](https://user-images.githubusercontent.com/123381354/231406442-ab90bb4a-7992-4434-ae05-54982d8f5f39.jpeg)

**Comment by datakalp** [comment]
Is this still happening?

**Comment by datakalp** [comment]
I got this multiple prompts again today. Recording made at 5:08 pm against kalpit@datakalp.com username.

**Comment by anubhutiGupta** [comment]
fixed this issue from frontend's side, can be closed after thorough testing

**Comment by anubhutiGupta** [comment]
Closing this as this is no more being reported
